server:
  port: 8081
  servlet:
    context-path: /feriavirtual
logging:
  level:
    root: info
    com:
      zaxxer:
        hikari:
          HikariConfig: DEBUG
      hibernate:
        type:
          descriptor:
           sql:
            BasicBinder: TRACE
spring:
  thymeleaf:
    enabled: true
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
  datasource:
    password: 123456789
    username: admin
    url: jdbc:oracle:thin:@database-feriavirtual.cvklypftqzjn.us-east-1.rds.amazonaws.com:1521/DATABASE
    driverClassName: oracle.jdbc.driver.OracleDriver